name: SelectiveRenderPlots
version: ${version}
main: de.selectiverender.plots.paper.SelectiveRenderPlotsPaperPlugin
api-version: '1.20'
depend: [PlotSquared]
authors: [cepreni-pengwing]
description: Sends exact PlotSquared regions to Selective Render clients.
permissions:
  selectiverender.plot.solo:
    description: Allows using Selective Render plot integration.
    default: true
